baseURL = "https://ericpena.github.io/"
languageCode = 'en-us'
title = "Eric Peña"
theme = "spectral"
paginate = 50

canonifyURLs=true
publishDir="docs"
relativeURLs = true

[params]
fancyTitle = "Eric Peña" # title for frontpage, may include image
copyright = "Eric Peña"
description = 'Senior Data Scientist<br />Understanding Complexity Through Data and Statistics'
startbuttonText = "Posts"
startbuttonLink = "/posts"
body_is_markdown = true
#custom_css = "foo.css"
#custom_sass = "bar.scss"
#images = ["path_to_social_image_for_link_previews.jpg"]

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/about/'
title = "About Me"

[[params.menu.main]]
url = '/posts/'
title = "Posts"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params.one]
enable = true
title = 'The Ohio State University – Physics<br />Binghamton University – Complex Systems'
body = '''
As a Senior Data Scientist in the autonomous vehicle industry, I specialize in statistical modeling of complex systems, 
with a strong focus on safety of engineering applications. My work integrates advanced data science methods with systems 
engineering principles to enhance the reliability and safety of autonomous systems. I am passionate about understanding 
how complex systems behave under uncertainty.
'''

[[params.one.icon]]
icon = "fa-gem"
style = "1"
label = "Lorem"

[[params.one.icon]]
icon = "fa-heart"
style = "2"
label = "Ipsum"

[[params.one.icon]]
icon = "solid fa-code"
style = "3"
label = "Dolor"

[params.two]
enable = false

[[params.two.section]]
img = "img/pic01.jpg"
img_alt = "blurry background: white/grey"
title = 'Magna primis lobortis<br />sed ullamcorper'
body = 'Aliquam ut ex ut augue consectetur interdum. Donec hendrerit imperdiet. Mauris eleifend fringilla nullam aenean mi ligula.'

[[params.two.section]]
img = "img/pic02.jpg"
title = 'Tortor dolore feugiat<br />elementum magna'
body = 'Aliquam ut ex ut augue consectetur interdum. Donec hendrerit imperdiet. Mauris eleifend fringilla nullam aenean mi ligula.'

[[params.two.section]]
img = "img/pic03.jpg"
title = 'Magna primis lobortis<br />sed ullamcorper'
body = 'Aliquam ut ex ut augue consectetur interdum. Donec hendrerit imperdiet. Mauris eleifend fringilla nullam aenean mi ligula.'

[params.three]
enable = false
title = 'Accumsan mus tortor nunc aliquet'
body = '''
Aliquam ut ex ut augue consectetur interdum. Donec amet imperdiet eleifend  
fringilla tincidunt. Nullam dui leo Aenean mi ligula, rhoncus ullamcorper.
'''

[[params.three.feature]]
icon = "fa-paper-plane"
title = "Arcu accumsan"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "solid fa-laptop"
title = "Ac Augue Eget"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "solid fa-code"
title = "Foo bar"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "solid fa-headphones-alt"
title = "Baz kram"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-heart"
title = "Some latin text"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-flag"
title = "Nothing important"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[params.cta]
enable = false
title = "Arcue ut vel commodo"
body = "Aliquam ut ex ut augue consectetur interdum endrerit imperdiet amet eleifend fringilla."

[[params.cta.link]]
href = "#"
text = "Activate"
special = true

[[params.cta.link]]
href = "#"
text = "Learn More"
special = false

[params.contact]
enable = false
title = "Contact"
body = "Feel free to reach out."
# phone = "+49 (0) 030 000 000"
# address = "1234 Somewhere Road<br />Some Place, Some State 0000<br />Some Country"
email = "eric.pena@binghamton.edu"
subject = "New Submission From Website!"
formspree_form_id = "example_invalid"

[params.social]
twitter = "ericpenax"
mastodon = "@ericpena"
github = "ericpena"
facebook = ""
youtube = ""
instagram = "ericpena"
dribble = ""
linkedin = "eric-pena"

# language specific options

[languages.en]
weight = 0
languageName = "English"

[languages.de]
weight = 10
languageName = "Deutsch"

[languages.es]
weight = 10
languageName = "Español"
